# import the libraries.

In [1]:
import numpy as np
import pandas as pd

# Read the dataset

In [3]:
ds= pd.read_csv('fuel consumption (1).csv')

In [4]:
ds.head()

distance consume  speed temp_inside  temp_outside specials gas_type  AC  \
0       28       5     26        21,5            12      NaN      E10   0   
1       12     4,2     30        21,5            13      NaN      E10   0   
2     11,2     5,5     38        21,5            15      NaN      E10   0   
3     12,9     3,9     36        21,5            14      NaN      E10   0   
4     18,5     4,5     46        21,5            15      NaN      E10   0   

   rain  sun refill liters refill gas  
0     0    0            45        E10  
1     0    0           NaN        NaN  
2     0    0           NaN        NaN  
3     0    0           NaN        NaN  
4     0    0           NaN        NaN

In [5]:
ds.tail()

distance consume  speed temp_inside  temp_outside specials gas_type  AC  \
383       16     3,7     39        24,5            18      NaN     SP98   0   
384     16,1     4,3     38          25            31       AC     SP98   1   
385       16     3,8     45          25            19      NaN     SP98   0   
386     15,4     4,6     42          25            31       AC     SP98   1   
387     14,7       5     25          25            30       AC     SP98   1   

     rain  sun refill liters refill gas  
383     0    0           NaN        NaN  
384     0    0           NaN        NaN  
385     0    0           NaN        NaN  
386     0    0           NaN        NaN  
387     0    0           NaN        NaN

# checking the null values

In [29]:
ds.isnull().sum().sum()

1057

In [30]:
ds['temp_inside']=ds['temp_inside'].fillna(ds['temp_inside'].mode()[0])
ds['specials']=ds['specials'].fillna(ds['specials'].mode()[0])
ds['refill liters']=ds['refill liters'].fillna(ds['refill liters'].mode()[0])
ds['refill gas']=ds['refill gas'].fillna(ds['refill gas'].mode()[0])


In [31]:
ds.isnull().sum().sum()

0

# Handling the null values

In [32]:
ds['distance'] = ds['distance'].str.replace(',', '').astype(int)
ds['consume'] = ds['consume'].str.replace(',', '').astype(int)
ds['temp_inside'] = ds['temp_inside'].str.replace(',', '').astype(int)
ds['refill liters'] = ds['refill liters'].str.replace(',', '').astype(int)

In [33]:
ds.drop(['specials','gas_type','refill gas'],axis=1,inplace=True)

In [34]:
ds=pd.get_dummies(ds,columns=['AC','rain','sun'])

In [35]:
ds.head()

distance  consume  speed  temp_inside  temp_outside  refill liters  AC_0  \
0        28        5     26          215            12             45     1   
1        12       42     30          215            13            377     1   
2       112       55     38          215            15            377     1   
3       129       39     36          215            14            377     1   
4       185       45     46          215            15            377     1   

   AC_1  rain_0  rain_1  sun_0  sun_1  
0     0       1       0      1      0  
1     0       1       0      1      0  
2     0       1       0      1      0  
3     0       1       0      1      0  
4     0       1       0      1      0

In [49]:
ds.tail()

distance  consume  speed  temp_inside  temp_outside  refill liters  AC_0  \
383        16       37     39          245            18            377     1   
384       161       43     38           25            31            377     0   
385        16       38     45           25            19            377     1   
386       154       46     42           25            31            377     0   
387       147        5     25           25            30            377     0   

     AC_1  rain_0  rain_1  sun_0  sun_1  
383     0       1       0      1      0  
384     1       1       0      1      0  
385     0       1       0      1      0  
386     1       1       0      1      0  
387     1       1       0      1      0

# separate independent and dependent null values

In [36]:
x=ds.drop(columns=['refill liters']).values
y=ds['refill liters'].values

# split the data into train and test

In [37]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# Applying Linear Regrssion

In [38]:
from sklearn.linear_model import LinearRegression
MLR =LinearRegression()
MLR.fit(x_train,y_train)

LinearRegression()

In [39]:
y_pred=MLR.predict(x_test)
y_pred

array([371.09822453, 369.52891412, 372.81172721, 372.17946749,
       367.34253902, 373.04517496, 378.169471  , 359.56031917,
       366.1323778 , 371.05193345, 371.7090758 , 370.60188799,
       375.58095768, 378.65371814, 365.11426182, 372.78673024,
       366.37937682, 365.93791535, 383.0809985 , 374.27301898,
       369.33066202, 367.23602709, 374.50887587, 369.80508745,
       381.78023746, 374.42750512, 374.41547511, 380.90769184,
       373.368048  , 369.64519702, 363.35385279, 373.40481226,
       371.49059575, 367.54171024, 370.90121432, 373.84133764,
       384.87074003, 365.55701603, 358.80586821, 370.33767572,
       371.81752993, 385.11441242, 372.43301231, 356.54312481,
       370.2118931 , 354.65478687, 370.84729778, 366.60124571,
       376.4039182 , 363.7747951 , 367.4806127 , 341.64819923,
       365.97343685, 365.94823951, 343.72046956, 364.70464327,
       376.58383472, 365.80585011, 377.80125722, 356.56859994,
       374.72932463, 365.69712801, 373.09503463, 372.80

In [40]:
pred=MLR.predict(x_train)
pred

array([358.95726197, 371.54610863, 376.51971701, 370.95857327,
       385.51215517, 368.20670812, 368.14902045, 369.80211038,
       366.01779735, 360.33355355, 371.01990444, 371.32256016,
       379.52946654, 368.82281868, 377.45633415, 371.91518378,
       356.38586393, 362.18416236, 371.35219211, 372.90247565,
       372.11023069, 372.2190534 , 364.66369596, 369.78607335,
       371.5715869 , 368.62779056, 373.63339547, 363.26187096,
       372.82653999, 369.47526112, 367.07039649, 372.7401349 ,
       386.8025232 , 378.85962382, 389.55363664, 382.52226173,
       370.29409421, 383.51234554, 375.12116077, 375.7196025 ,
       363.90235465, 373.54468292, 387.09112941, 355.44914043,
       370.60966659, 379.04420604, 375.68321245, 362.60680824,
       353.93807899, 367.79841244, 370.0905516 , 370.57979047,
       367.31304037, 375.30224016, 367.32463126, 364.72753744,
       370.44676224, 362.43316841, 367.63284961, 372.72006431,
       366.54987705, 369.55566554, 348.93798675, 358.93

In [41]:
from sklearn.metrics import r2_score

acc=r2_score(y_test,y_pred)

acc

0.09512698789074969

In [42]:
MLR.predict([[34,4,56,315,1,0,0,0,0,0,1]])

array([377.31226895])

In [43]:
import pickle

In [44]:
pickle.dump(MLR,open('/content/b','wb'))

In [47]:
ml=pickle.load(open('f','rb'))

In [48]:
ml.predict(x_test)

array([371.09822453, 369.52891412, 372.81172721, 372.17946749,
       367.34253902, 373.04517496, 378.169471  , 359.56031917,
       366.1323778 , 371.05193345, 371.7090758 , 370.60188799,
       375.58095768, 378.65371814, 365.11426182, 372.78673024,
       366.37937682, 365.93791535, 383.0809985 , 374.27301898,
       369.33066202, 367.23602709, 374.50887587, 369.80508745,
       381.78023746, 374.42750512, 374.41547511, 380.90769184,
       373.368048  , 369.64519702, 363.35385279, 373.40481226,
       371.49059575, 367.54171024, 370.90121432, 373.84133764,
       384.87074003, 365.55701603, 358.80586821, 370.33767572,
       371.81752993, 385.11441242, 372.43301231, 356.54312481,
       370.2118931 , 354.65478687, 370.84729778, 366.60124571,
       376.4039182 , 363.7747951 , 367.4806127 , 341.64819923,
       365.97343685, 365.94823951, 343.72046956, 364.70464327,
       376.58383472, 365.80585011, 377.80125722, 356.56859994,
       374.72932463, 365.69712801, 373.09503463, 372.80